### ISSUE TITLE
HALO Jump

### ISSUE THREAD

**Issue by olumby** [olumby/unknown#1]
These would work as an alternative to spawn beacons.

A player places an object on the ground, team/group players can then use this object as a spawn location. They spawn in a bubble around the object at about 1000m in altitude with a parachute set to auto deploy at about 250m.

To make HALO spawns more obvious at night, players could have a chemlight attached to them as they fall. The object could also have a light on it. It could also be found by players with a toolkit.

**Comment by PR3SIDENT** [comment]
I like the idea of the HALO Spawn, I think it's really a cool affect and could make the feel of this a lot more tactical than just a TDM mode. However, my concern is that its very easy to spot/shoot people down in parachutes.

At night, if we do the chemlights we need to make them disable when the chute opens. I feel like it would be a turkey shoot. Even during the day, parachutes are so obvious I just wonder if it will result in more fresh spawn killing.

I guess one way to mitigate this would be spread the spawning locations in such a random way the chances of being shot while spawning would be low.

**Comment by olumby** [comment]
I don't think it would be appropriate to replace usual town and random player spawns, just group/team placed spawn locations.

We could spawn players randomly within a 2-300m bubble of the spawn, with the ~750m of freefall movement and another ~250m of steerable parachute, they'd have plenty of time to move without getting shot.

**Comment by PR3SIDENT** [comment]
We discussed the HALO drop coordinating with team colour. I think it's a good idea, both the Smoke  and ChemLight to share the teams colour. This will make identifying hostiles by color or by light much easier when looking up as opposed to a unified color. 

Which btw is an alternative we could just use something like "Purple" and not bother with colors if that becomes too unbalanced or a problem.

**Comment by olumby** [comment]
HALO Jumps are now implemented and can be color coordinated.

See eda7cff
