### ISSUE TITLE
Vote/Poll System

### ISSUE THREAD

**Issue by PR3SIDENT** [olumby/unknown#3]
One thing I like about playing in Battlefield servers is the ability for the players to have an impact on the Map rotation. Since ARMA doesn't really have a map rotation, I think it would be cool for players to be able to contribute to things such as the following:
- Weather Changes
- Time of Day Changes
- Mission Spawns
- Flag Locations (if we do flags)

Players would not be able to initiate these votes/polls, but would be presented with an option at random times during the match.

**Comment by olumby** [comment]
This is probably more of an external tool that would run separately using the admin console, but opening it would be interesting. 

That said, I find it annoying when you play in night/bad weather servers and players ask the admins to change it to day/sunny just because it is easier..
