### ISSUE TITLE
Flag Finances

### ISSUE THREAD

**Issue by olumby** [olumby/unknown#4]
An idea for flag based finances.

Each objective has an interior bubble and an exterior bubble, for example 500m interior and 1km exterior. To capture or contest the objective you must be inside the interior bubble.

Capture Objective - 2000
Obj Defence (interior/exterior) (control obj, tick every 2 minutes) - 500
Obj Attack (interior/exterior) (don't control obj, tick every 2 minutes) - 100
Obj Defence Kill - (interior/exterior) (control obj, tick every 2 minutes) - 200
Obj Attack Kill (interior/exterior) (don't control obj, tick every 2 minutes) - 100

More of a Battlefield/KOTH style reward system. I think it would be more rewarding and make the flags more attractive.

**Comment by faffelkugel** [comment]
Where's the Like button? ;)

EDIT: As in, that sounds cool.
