### ISSUE TITLE
Forget hunger... Energy is the key.

### ISSUE THREAD

**Issue by PR3SIDENT** [olumby/unknown#6]
I've never liked the drink/food system in Wasteland. It's never been balance right to have relevance with survival time vs depletion time. One thing I don't really like right now is that people can sprint/run for days with no impact. But I also hate exhaustion systems in other game modes we play (like KoTH).

So begs the question? What's a good balance? 

IMO: I think we should find a way to display energy, and the more you sprint the more energy you use. However, the impact of having no energy isn't being able to sprint... It's a visual impact, such as your guy sitting down or passing out at times. We could agree on the impact of this and how often... it could also be a visual change such as blackouts etc. I don't want people to be running out of energy, but it's pretty annoying watching a guy with a pack of full gear sprint around with no impact at all.

For example, to regain energy could be as simple as sitting or laying down for 3-5 seconds and then recharged. I just dont think people should be able to sprint for 15 minutes and never stop.

**Comment by olumby** [comment]
Personally, I hate the whole concept of fatigue and think it should stay out of core. If a server wants to adjust the system, they can.

I think in modes like KOTH it is important to stop players being able to just run around the objective without any consequences but with an open world the size of Altis it is a little diferent. If your vehicle breaks down and you have a 4km run to the nearest town with no energy/food/water so can only run 500m at a time before you pass out, I for sure am just going to respawn.

I think as long as the aiming effects remain (being unable to look straight down the sights after running) it isn't too bad.
