### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by PR3SIDENT** [olumby/unknown#9]
If we want to drive adoption of our mod we need to give server providers and clans/communities to brand our mod to their liking. This would include but not be limited to the following:
- Custom Images on Billboard/Signs in game
- Customization of loading images (server)
- Help text (things like teamspeak information or administrator lists)
- Mission portfolio selection (choose from a list of missions we've made available)
- Vehicle variation configuration (add/remove skins/variants to vehicles)

The idea is that we'd make this as easy as possible for people who may not be completely familiar with how to code and embed these images within the game. Perhaps even a easy to use utility for them to select where they want each image and a description of where in the game it will go.

**Comment by faffelkugel** [comment]
I don't really like the idea of billboards in the game, as I feel it disrupts the experience in a sense that it would feel unnatural with a random server promotion in a game where you're trying to be immersed into the ongoing battle.

Also I can see the billboards being abused, and used for inappropriate content, such as pornographic material, or other offensive material.

Furthermore, billboards seems to be a very american thing, and I don't see it fitting into the environment of Altis or Stratis.

I feel kinda the same way with vehicle skins, but not really.

**Comment by olumby** [comment]
> - Custom Images on Billboard/Signs in game
> - Customization of loading images (server)

Any server admin can easily do these things, there are plenty of guides online.

> - Help text (things like teamspeak information or administrator lists)

Eventually all strings in the game will be moved to a localisation file, this would also serve for this.

> - Mission portfolio selection (choose from a list of missions we've made available)
> - Vehicle variation configuration (add/remove skins/variants to vehicles)

Available missions will be available to override in a config file in `overrides` and vehicle variations will be configurable in the `map` folder.

I feel the same way as @faffelkugel regarding immersion, pink striders and in your face advertisements are a little stupid in my opinion. I plan to only set up realistic vehicle variations and a few subtle sign posts, but again any admin who can edit a text document can add in whatever they like.

**Comment by Jrb1x** [comment]
The cake is not on the wooded-yellow trail like you suggested.
